remote_theme: thelehhman/plainwhite-jekyll

plainwhite:
        name: John J.H Kim
        tagline: Immunologist. Biomedical Data Scientist
        date_format: "%b %-d, %y"

        social_links:
                github: kimjhkp
                linkedIn: in/kimjhk

